apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    environment: ${NAMESPACE}
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
  type: ClusterIP