# build-orchestrator.yml
name: Reusable Build Stage Orchestrator

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      repo_name:
        required: true
        type: string
    outputs:
      full_image_tag:
        value: ${{ jobs.set_build_vars.outputs.full_image_tag }}
      aks_namespace:
        value: ${{ jobs.set_build_vars.outputs.aks_namespace }}
      image_tag:
        value: ${{ jobs.set_build_vars.outputs.image_tag }}
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

# build-orchestrator.yml
jobs:
  set_build_vars:
    runs-on: ubuntu-latest
    outputs:
      full_image_tag: ${{ steps.set_image_info.outputs.full_image_tag }}
      aks_namespace: ${{ steps.set_image_info.outputs.aks_namespace }}
      image_tag: ${{ steps.set_image_info.outputs.image_tag }}

    steps:
      - name: Set Image Tag and AKS Namespace
        id: set_image_info
        run: |
          IMAGE_TAG=""
          AKS_NAMESPACE=""
          ACR_REGISTRY="${{ vars.AZURE_CONTAINER_REGISTRY }}"
          ACR_RESOURCE_GROUP="${{ vars.RESOURCE_GROUP }}"

          TARGET_ENV_NAME="${{ inputs.target_environment }}"

          echo "=== DEBUG INFO ==="
          echo "Target Environment: $TARGET_ENV_NAME"
          echo "Repository Name: ${{ inputs.repo_name }}"
          echo "ACR Registry: $ACR_REGISTRY"

          if [[ "$TARGET_ENV_NAME" == "dev" ]]; then
            IMAGE_TAG="dev"
            AKS_NAMESPACE="dev"
          elif [[ "$TARGET_ENV_NAME" == "production" ]]; then
            IMAGE_TAG="stable"
            AKS_NAMESPACE="production"
          else
            echo "Error: Invalid target_environment '$TARGET_ENV_NAME'. Must be 'dev' or 'production'."
            exit 1 
          fi

          FULL_IMAGE_NAME="$ACR_REGISTRY.azurecr.io/${{ inputs.repo_name }}:$IMAGE_TAG"

          echo "=== GENERATED VALUES ==="
          echo "Image Tag: $IMAGE_TAG"
          echo "AKS Namespace: $AKS_NAMESPACE"
          echo "Full Image Name: $FULL_IMAGE_NAME"

          echo "full_image_tag=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "aks_namespace=$AKS_NAMESPACE" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  build_docker:
    needs: set_build_vars
    uses: ./.github/workflows/build.docker.yml
    with:
      image_name: ${{ inputs.repo_name }}
      image_tag: ${{ needs.set_build_vars.outputs.image_tag }}
      acr_registry: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      acr_resource_group: ${{ vars.RESOURCE_GROUP }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}