# cicd-tools/.github/workflows/build.docker.yml
name: Build and Push to ACR

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: 'Name of the Docker image (e.g., your-repo-name)'
      image_tag: # <<-- CHANGED: Now an input, not from vars.IMAGE_TAG
        required: true
        type: string
        description: 'Dynamic tag for the Docker image (e.g., dev-SHA, prod-SHA)'
      acr_registry: # <<-- CHANGED: Now an input
        required: true
        type: string
        description: 'Name of your container registry / ACR'
      acr_resource_group: # <<-- CHANGED: Now an input
        required: true
        type: string
        description: 'Resource group where your ACR is deployed'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push to ACR
        run: |
          # Uses inputs for registry and resource group
          FULL_IMAGE_NAME="${{ inputs.acr_registry }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          echo "Building and pushing image: $FULL_IMAGE_NAME"
          az acr build --image "$FULL_IMAGE_NAME" \
                       --registry ${{ inputs.acr_registry }} \
                       -g ${{ inputs.acr_resource_group }} .