# cicd-tools/.github/workflows/build.docker.yml
name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: 'Name of the Docker image (e.g., your-repo-name)'
      image_tag:
        required: true
        type: string
        description: 'Tag for the Docker image (e.g., SHA, dev-SHA, prod-SHA)'
      acr_registry_name: 
        required: true
        type: string
        description: 'Azure Container Registry name (e.g., myorgacr)'
      acr_resource_group: 
        required: true
        type: string
        description: 'Azure Resource Group name for ACR'
    secrets:
      AZURE_CLIENT_ID: 
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push to ACR
        run: |
          FULL_IMAGE_NAME="${{ inputs.acr_registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          echo "Building and pushing image: $FULL_IMAGE_NAME"
          az acr build --image "$FULL_IMAGE_NAME" \
                       --registry ${{ inputs.acr_registry_name }} \
                       -g ${{ inputs.acr_resource_group }} .