name: Reusable Main CI/CD Pipeline

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read 
  id-token: write
  actions: write 

jobs:
  evaluate_ci_cd_rules:
    name: Evaluate Branch Rules
    runs-on: ubuntu-latest # Add this line back
    outputs: # Add this outputs block
      should_run_build: ${{ jobs.evaluate_ci_cd_rules.outputs.should_run_build }}
      should_run_deploy: ${{ jobs.evaluate_ci_cd_rules.outputs.should_run_deploy }}
      target_environment: ${{ jobs.evaluate_ci_cd_rules.outputs.target_environment }}
    uses: ./.github/workflows/rules.yml

  orchestrate_build:
    name: Orchestrate Build Stage
    needs: evaluate_ci_cd_rules
    if: needs.evaluate_ci_cd_rules.outputs.should_run_build == 'true'
    uses: ./.github/workflows/build-orchestrator.yml
    with:
      target_environment: ${{ needs.evaluate_ci_cd_rules.outputs.target_environment }}
      repo_name: ${{ github.event.repository.name }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy_np:
    name: Deploy to Non-Production (Dev)
    needs: [evaluate_ci_cd_rules, orchestrate_build]
    if: |
      needs.evaluate_ci_cd_rules.outputs.should_run_deploy == 'true' &&
      needs.evaluate_ci_cd_rules.outputs.target_environment == 'dev'
    uses: ./.github/workflows/deploy.acr.yml
    with:
      target_env_name: dev
      image_full_tag: ${{ needs.orchestrate_build.outputs.full_image_tag }}
      resource_group: ${{ vars.RESOURCE_GROUP }}
      cluster_name: ${{ vars.CLUSTER_NAME }}
      namespace: ${{ needs.orchestrate_build.outputs.aks_namespace }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy_prod:
    name: Deploy to Production
    needs: [evaluate_ci_cd_rules, orchestrate_build]
    if: |
      needs.evaluate_ci_cd_rules.outputs.should_run_deploy == 'true' &&
      needs.evaluate_ci_cd_rules.outputs.target_environment == 'production'
    uses: ./.github/workflows/deploy.acr.yml
    with:
      target_env_name: production
      image_full_tag: ${{ needs.orchestrate_build.outputs.full_image_tag }}
      resource_group: ${{ vars.RESOURCE_GROUP }}
      cluster_name: ${{ vars.CLUSTER_NAME }}
      namespace: ${{ needs.orchestrate_build.outputs.aks_namespace }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}