name: Reusable Main CI/CD Pipeline

on:
  workflow_call:
    inputs:
      # Allow customization of ACR and AKS settings
      acr_name:
        required: false
        type: string
        description: 'Azure Container Registry name (if not provided, will use vars.AZURE_CONTAINER_REGISTRY)'
      resource_group:
        required: true
        type: string
        description: 'Resource group containing AKS cluster'
      cluster_name:
        required: true
        type: string
        description: 'AKS cluster name'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  evaluate_ci_cd_rules:
    name: Evaluate Branch Rules
    uses: ./.github/workflows/rules.yml

  orchestrate_build:
    name: Orchestrate Build Stage
    needs: evaluate_ci_cd_rules
    if: needs.evaluate_ci_cd_rules.outputs.should_run_build == 'true'
    uses: ./.github/workflows/build-orchestrator.yml
    with:
      target_environment: ${{ needs.evaluate_ci_cd_rules.outputs.target_environment }}
      repo_name: ${{ github.event.repository.name }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    name: Deploy to Environment
    needs: [evaluate_ci_cd_rules, orchestrate_build]
    if: needs.evaluate_ci_cd_rules.outputs.should_run_deploy == 'true'
    uses: ./.github/workflows/deploy.acr.yml
    with:
      target_env_name: ${{ needs.evaluate_ci_cd_rules.outputs.target_environment }}
      namespace: ${{ needs.evaluate_ci_cd_rules.outputs.namespace }}
      cluster_name: ${{ inputs.cluster_name }}
      resource_group: ${{ inputs.resource_group }}
      image_full_tag: ${{ github.event.repository.name }}:${{ needs.evaluate_ci_cd_rules.outputs.image_tag }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
